name: Pulse-keeper CI/CD Pipeline

on:
  push:
    branches:
      - cicd-setup
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    environment: ${{ github.ref == 'refs/heads/cicd-setup' && 'cicd-setup' || github.ref == 'refs/heads/stage' && 'stage' || github.ref == 'refs/heads/prod' && 'prod' || '' }}
      
    steps:   
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set up Python 3.11
          uses: actions/setup-python@v3
          with:
            python-version: "3.11"
        
        - name: Install dependencies
          run: |
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

        - name: Run tests
          run: |
            echo ${{ github.head_ref || github.ref_name }}
            echo "Tests ran."

        - name: Deploy
          if: github.event_name == 'push'
          env: 
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: ${{ vars.AWS_REGION }}
            AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
          run: |
            echo $AWS_ACCESS_KEY_ID
            echo $AWS_SECRET_ACCESS_KEY
            echo $AWS_REGION
            echo $AWS_ACCOUNT_ID
            echo "Project deployed."