name: Pulse-keeper CI/CD Pipeline

on:
  push:
    branches:
      - cicd-setup
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:   
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Set up Python 3.11
          uses: actions/setup-python@v3
          with:
            python-version: "3.11"
        
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ env.sandbox.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ env.sandbox.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1

        - name: Success message
          run: |
            echo "It works!"